apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: vnf7arl4b-go
  janus-idp.io/tekton: vnf7arl4b-go
  backstage.io/kubernetes-id: vnf7arl4b-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vnf7arl4b-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
